### ISSUE TITLE
How did you decide on x,y and velocity of ball to predict bounces?

### ISSUE THREAD

**Issue by nyck33** [ArtLabss/tennis-tracking#11]
_To predict bounce points machine learning library for time series sktime was used. Specifically, TimeSeriesForestClassifier was trained on 3 variables: x, y coordinates of the ball and V for velocity (V2-V1/t2-t1). 
**Additional context**
Add any other context or screenshots about the feature request here._

I want to try to improve the predictive accuracy but don't want to reinvent the wheel if you can share some info on what you tried and how you decided on these three factors.

**Comment by shukkkur** [comment]
@nyck33 Hey, thanks for opening the issue! Yep, predicting bounces sure took me a while.
So, assuming we have `x`,`y` coordinates stored in lists from the [prediction.py](https://github.com/ArtLabss/tennis-tracking/blob/main/predict_video.py) script
```python
186   x = int(circles[0][0][0])
187   y = int(circles[0][0][1])
```
I tried different methods:
- I thought of extracting the local minimum and maximum will give the bounces points.
![image](https://user-images.githubusercontent.com/78250180/141716135-394a297f-fa1a-409d-8a37-f72ef383aa0f.png)
_red points - bounces_
After finding the min and max and plotting them together with bounces  shows that it captured some bounces,  but not all.
- Then we tried extracting the point where change in ball's velocity happens.
![image](https://user-images.githubusercontent.com/78250180/141716333-05cb3af8-bf71-43d4-8055-5cf6aa8f9b7c.png)
Turn out not helpful either.
- Looking at the previous graphs a certain pattern can be observed. We tried using sklearn models as well with. However, it couldn't capture the underlying pattern.
_`df['x'].shift(1)....df['x'].shift(20)`_ - for 20 features
![image](https://user-images.githubusercontent.com/78250180/141718033-12f3fb45-bfd7-41be-bd59-a8a7426b9f2b.png)

-  that's why we decided to use time series which captures the relationship between preceding and following ball's `x,y` coordinates.  We experimented with [sktime](https://sktime.org/) time series classification methods such as `TimeSeriesForestClassifier()` and `KNeighborsTimeSeriesClassifier()` and with different number of features 
**Univariate** **Classification** - predicting using just: 
- x
- y
- V
**Multivariate Classification** 
- x,y 
- x, y, V
Out of all the best result gave us using `TimeSeriesForestClassifier()` and `x`,`y` and `V`. 

That's generally all the methods we have tried. If there is anything else you would like to know, let us know!

**Comment by nyck33** [comment]
I tried a Kalman filter using that first plot you have up but that led nowhere.  Over 80% is already pretty impressive but thanks for the clarification.

**Comment by nyck33** [comment]
@shukkkur This guy https://github.com/taikoma predicted bounce location using SVM and I believe it was trajectory.  He had a blog post on https://qiita.com/ (in Japanese) which I was looking for and can't find anymore.  
But I remember his demo video was with the camera more behind the court (not so much from above like broadcast) and it was of a serve from the other side and he had nailed the location.

**Comment by nyck33** [comment]
@shukkkur have you seen this: https://arxiv.org/abs/2008.04524

**Comment by shukkkur** [comment]
> @shukkkur have you seen this: https://arxiv.org/abs/2008.04524

No, I haven't. Thank you for sharing. Will make sure to have a look at it.

**Comment by shukkkur** [comment]
> @shukkkur This guy https://github.com/taikoma predicted bounce location using SVM and I believe it was trajectory. He had a blog post on https://qiita.com/ (in Japanese) which I was looking for and can't find anymore. But I remember his demo video was with the camera more behind the court (not so much from above like broadcast) and it was of a serve from the other side and he had nailed the location. I only mention this because although I am not as good at ML as you guys, I have a background in tennis coaching so want to extend what you have for a coaching app but ideally having 90 to 95% of the bounces.

I am not good either, just an intern that doesn't understand half of what he does) 
wow 90-95% is really something. Good Luck with that!
